pipeline {
  environment {
  registry = "sonpham170199/nodejs"
  }
  agent any
  stages {
    stage('Ansible Ping') {
      steps {
            sh "cd ./ansible/first-playbook && ansible -i inventory centos -m ping \
            && ansible-playbook install-pkg/packages.yaml"
      }
    }
    stage('Ansible Install Packages') {
      steps {
            sh "ansible-playbook ansible/first-playbook/install-pkg/packages.yaml"
      }
    }
  }
}