pipeline {
  environment {
  registry = "sonpham170199/nodejs"
  }
  agent any
  stages {
    stage('Ansible Ping') {
      steps {
            sh "cd ./ansible/first-playbook && echo Ilab.vn171 | ansible centos -u admin02 --ask-pass -m ping"
      }
    }
  }
}