- hosts: all
  user: admin02
  become: True
  tasks:
    - name: Install Packages
      yum:
        name: 
        - httpd
        - nano
        - wget
        - vim
        - chronyd
        state: present
        update_cache: True
