FROM ubuntu:jammy

LABEL maintainer="Son Pham Hoang Thanh <sonpham170199@outlook.com>"

# Static Applications.
RUN apt-get update && \
    apt-get -qy full-upgrade && \
    apt-get install -qy \
    git \
    openjdk-8-jdk \
    curl \
    maven \
    python3 \
    python3-pip \
    python3-setuptools \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    epel-release \
    sshpass

# Add Docker's official GPG key
RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg  && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

RUN pip3 install --upgrade pip && \
    pip3 install cffi && \
    pip3 install ansible
    
# Install AWS CLI 
RUN pip3 install awscliv2
    
# Install a basic SSH server
RUN apt-get install -qy openssh-server && \
    sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd && \
    mkdir -p /var/run/sshd && \
# Add user jenkins to the image
    useradd -m jenkins -p 200699 && \
# Creat M2 directory
    cd /home/jenkins && \
    mkdir .m2

#ADD settings.xml /home/jenkins/.m2/
# Copy authorized keys
COPY .ssh/authorized_keys /home/jenkins/.ssh/authorized_keys

RUN chown -R jenkins:jenkins /home/jenkins/.m2/ && \
    chown -R jenkins:jenkins /home/jenkins/.ssh/
    
# Add Jenkins permission to able to use Docker
RUN usermod -a -G docker jenkins
    
# Cleanup old packages
RUN apt-get autoremove

# Standard SSH port
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]